// <auto-generated />
namespace portfolio_career_development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userDB_back_to_default : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userDB_back_to_default));
        
        string IMigrationMetadata.Id
        {
            get { return "202011031638521_userDB_back_to_default"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
