// <auto-generated />
namespace portfolio_career_development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ArticleModelUpdated_Mutlilinetext_content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArticleModelUpdated_Mutlilinetext_content));
        
        string IMigrationMetadata.Id
        {
            get { return "202011011618280_ArticleModelUpdated_Mutlilinetext_content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
